# Generated by Django 3.2.9 on 2021-12-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores_api', '0001_initial'),
        ('items_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores_api.store'),
        ),
    ]
