# Generated by Django 3.2.9 on 2021-12-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0002_item_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
    ]
