# Generated by Django 3.2.9 on 2021-12-08 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
